apiVersion: v1
kind: ConfigMap
metadata:
  name: $APP_NAME-configmap
  namespace: $NS_NAME
  labels:
    app: $APP_NAME
  annotations:
    rebuild: "true"
data:
  GREET: 'Hola mundo'
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: $APP_NAME
  strategy: {}
  template:
    metadata:
      labels:
        deployment: $APP_NAME
    spec:
      containers:
      - image: $IMAGE_NAME$IMAGE_VERSION
        name: $APP_NAME
        envFrom:
        - secretRef:
            name: $APP_NAME-secret
        - configMapRef:
            name: $APP_NAME-configmap
        env:
        - name: MYSQL_DATABASE
          value: "hello"
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: mysql
--- 
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
spec:
  port:
    targetPort: $APP_PORT-tcp
  to:
    kind: Service
    name: $APP_NAME
